### ISSUE TITLE
vim-easymotion doesn't work with dein#add()

### ISSUE THREAD

**Issue by rhysd** [Shougo/dein.vim#31]
# Problem summary

vim-easymotion doesn't work with `dein#add()`.  It does nothing on `<Plug>(easymotion-overwin-f2)`.

## Expected

vim-easymotion is available with dein.vim.

## Environment Information
 * OS: OS X 10.11.3
 * Vim version: NVIM 0.1.2 (in terminal)

## Provide a minimal .vimrc with less than 50 lines (Required!)

```vim
set runtimepath^=~/.config/dein/repos/github.com/Shougo/dein.vim
call dein#begin(expand('~/.cache/dein'))
call dein#add('easymotion/vim-easymotion')
call dein#end()
filetype plugin indent on
map m <Plug>(easymotion-overwin-f2)
```

## The reproduce ways from Vim starting (Required!)

 1. `rm -rf ~/.cache/dein/*` to ensure this is not related to cache
 2. `:call dein#install()` to install vim-easymotion
 3. Close `nvim` window with `:q`
 4. Open `nvim`
 5. Enter `m` in normal mode

## Screen shot (if possible)

N/A

## Upload the log messages by `:redir` and `:message`

N/A

----------------

I tried adding `vim-easymotion` directory to `&rtp` manually and it worked correctly.  It ensures this is a problem of dein.vim.  Revision of dein.vim is 0a2803d and revision of easymotion is [`649120e`](https://github.com/easymotion/vim-easymotion/commit/649120e90e92bc2ae5361693fa1e4dd2d02c1822).

@haya14busa
If you have additional information, please give it to solve this issue.

**Comment by Shougo** [comment]
I cannot reproduce the error.
I think it is copy error.  It is fixed in latest version.
Please update dein.vim.

**Comment by haya14busa** [comment]
I didn't try dein.vim yet, but I found some reports that easymotion doesn't work with dein.vim.
So, I think it's true that there is something wrong with dein.vim or easymotion.

From a quick read of some tweet report, it might be fixed with lazy loading.

- https://twitter.com/yoza_is12s/status/705777019066257409
- https://twitter.com/yoza_is12s/status/705780665208348672

@rhysd

1. Can you try lazy-loading easymotion and the problem still exists or not?
2. Can you describe more detail about the problem? What does `vim-easymotion doesn't work` means?
  - plugin/easymotion.vim is not sourced
  - easymotion's mappings doesn't defined
  - Error occurs? (e.g. https://twitter.com/yoza_is12s/status/705580007934918657)
  - etc..

**Comment by rhysd** [comment]
@Shougo 

OK, I'll try this again with my clean environment.

@haya14busa 

> 1. Can you try lazy-loading easymotion and the problem still exists or not?

Still exists.

> 2. Can you describe more detail about the problem? What does vim-easymotion doesn't work means?

I mean *do nothing* as described above.  When I entered `m`, nothing happened.  Yeah, I will add more information for this if possible after trying above @Shougo's request.

**Comment by haya14busa** [comment]
You can confirm the mapping is defined or not by `:verbose nmap <Plug>(easymotion-overwin-f2)`.
There are some cases that the plugin doesn't work, and I want more detail report. 

In addition to `:verbose nmap...`, you can see `:scriptnames` and you can confirm plugin/easymotion.vim is sourced or not.

**Comment by rhysd** [comment]
@haya14busa 

Definitely.  I'm not having the environment to reproduce this now.  I'll check later.

**Comment by rhysd** [comment]
Sorry, let me confirm this tomorrow.

**Comment by rhysd** [comment]
I tried this again in another clean OS X environment and it worked fine with the latest dein.vim.  Thanks.
