### ISSUE TITLE
"No matching autocommands" when resourcing init.vim

### ISSUE THREAD

**Issue by SevereOverfl0w** [Shougo/dein.vim#349]
# Problems summary 

When running `:source $MYVIMRC` with dein, you get message `"No matching autocommands"`. This happens a lot more frequently with the auto recache.

## Expected

No autocommands message

## Environment Information (Required!)

 * dein.vim version(SHA1): 481cb4aebdd754a819cfe9b3b101a17d73548713

 * OS: Linux

 * Vim/neovim version: NVIM v0.3.8

## Provide a minimal .vimrc with less than 50 lines (Required!)

```vim
if &compatible
  set nocompatible
endif
" Add the dein installation directory into runtimepath
set runtimepath+=~/.cache/dein/repos/github.com/Shougo/dein.vim

call dein#begin('~/.cache/dein')

call dein#add('~/.cache/dein/repos/github.com/Shougo/dein.vim')
call dein#end()

filetype plugin indent on
syntax enable
```

## The reproduce ways from Vim starting (Required!)

1. vim -u /tmp/repro.vim
2. `:source /tmp/repro.vim`

**Comment by Shougo** [comment]
Sorry.  I cannot reproduce your problem.
Please check you have tested the vimrc.

**Comment by Shougo** [comment]
> This happens a lot more frequently with the auto recache.

Yes, because auto recache loads your configuration.

**Comment by Shougo** [comment]
You have not uploaded minimal vimrc.
So I will close it.

Please read the issue template.

**Comment by Shougo** [comment]
It means:

If I cannot reproduce the problem with vimrc.

```vim
if &compatible
  set nocompatible
endif
" Add the dein installation directory into runtimepath
set runtimepath+=~/.cache/dein/repos/github.com/Shougo/dein.vim

call dein#begin('~/.cache/dein')

call dein#add('~/.cache/dein/repos/github.com/Shougo/dein.vim')
call dein#end()

filetype plugin indent on
syntax enable
```

I can close it.

**Comment by Shougo** [comment]
> "No matching autocommands" when resourcing init.vim 

It should be fixed.  But it must be reproduce-able for me.

**Comment by SevereOverfl0w** [comment]
For me, that file reproduces the issue. There must be something additionally environmental. I tried moving my `~/.config/nvim` to `~/.config/nvim.bak` to rule that out, but no luck.

**Comment by Shougo** [comment]
OK.  Reproduced.

**Comment by SevereOverfl0w** [comment]
How did you reproduce, that you couldn't before?

**Comment by Shougo** [comment]
loading dein.vim seems must.

**Comment by Shougo** [comment]
Fixed.

**Comment by SevereOverfl0w** [comment]
Works, great, thanks!

**Comment by rafi** [comment]
@Shougo I'm still experiencing the message _"No matching autocommands"_ when opening the first file in a fresh new neovim. I've identified the problem to be `on_path = .*`, which I replaced with `on_event = BufRead` and the "issue", message, isn't appearing now.

**Comment by Shougo** [comment]
@rafi Have you read the issue properly??
You have not upload the reproducible vimrc.
I don't work for non reproducible problems.

**Comment by Shougo** [comment]
@rafi Please test the latest version of dein.vim.

**Comment by rafi** [comment]
Thanks @Shougo, your last commits fixes this issue. 🙏
