### ISSUE TITLE
Installation of latest released tag with `'rev': '*'` not working

### ISSUE THREAD

**Issue by mkobayashime** [Shougo/dein.vim#458]
# Problems summary

I'd like to use a plugin ([akinsho/git-conflict.nvim](https://github.com/akinsho/git-conflict.nvim)) which recommends using the latest released tag.
I specified `'rev': '*'` as written in the docs of dein (`*dein-option-rev*`), but dein is still installing the latest `main`. I tried adding `'type': 'git'` just in case, but the result is the same.

## Expected

Installation of the latest tag (`v1.0.0` in this case)

## Environment Information (Required!)

- dein.vim version(SHA1): 9d0948b7b44895b2079085e6639c8ced0e108316

- OS: Ubuntu 20.04

- neovim/Vim `:version` output:

```
NVIM v0.7.2
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -DNVIM_TS_HAS_SET_ALLOCATOR -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wdouble-promotion -
Wmissing-noreturn -Wmissing-format-attribute -Wmissing-prototypes -Wimplicit-fallthrough -Wsuggest-attribute=pure -Wsuggest-attribute=const -Wsuggest-attribute=malloc -Wsuggest-attribute=cold -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color
=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/mkobayashime/Downloads/neovim/build/config -I/home/mkobayashime/Downloads/neovim/src -I/home/mkobayashime/Downloads/neov
im/.deps/usr/include -I/usr/include -I/home/mkobayashime/Downloads/neovim/build/src/nvim/auto -I/home/mkobayashime/Downloads/neovim/build/include
Compiled by mkobayashime@rena

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/share/nvim"

Run :checkhealth for more info
```

## Provide a minimal init.vim/vimrc without plugin managers (Required!)

```vim
let s:cache_home = empty($XDG_CACHE_HOME) ? expand('~/.cache') : $XDG_CACHE_HOME
let s:dein_path = s:cache_home . '/dein'
let s:dein_repo_path = s:dein_path . '/repos/github.com/Shougo/dein.vim'
execute 'set runtimepath+=' . s:dein_repo_path

call dein#begin(s:dein_path)
call dein#add('akinsho/git-conflict.nvim', { 'rev': '*' })
call dein#end()

if dein#check_install()
  call dein#install()
endif
```

## How to reproduce the problem from neovim/Vim startup (Required!)

1. Wait until `dein#install()` finishes

**Comment by Shougo** [comment]
I will check it.

**Comment by Shougo** [comment]
Fixed.

**Comment by mkobayashime** [comment]
Thanks a lot for the quick response!

**Comment by mkobayashime** [comment]
@Shougo 
It's still not working for me (with the minimal `init.vim` above), could you take a look?
I confirmed dein itself is the latest (90cdafbc4357f78f14b1f2035279db11eb178159).

**Comment by Shougo** [comment]
Reproduced.  I have get the reason.

**Comment by Shougo** [comment]
Fixed.

**Comment by mkobayashime** [comment]
It's working correctly for sure now. Thank you so much.
