### ISSUE TITLE
can't access dein documentation

### ISSUE THREAD

**Issue by PaBLoX-CL** [Shougo/dein.vim#8]
I followed the instruccions on how to install dein:

```vim
let s:dein_path = expand('$CACHE/dein/repos/github.com/Shougo/dein.vim')
execute 'set runtimepath^=' . s:dein_path

call dein#begin(expand('$CACHE/dein'))

if dein#load_cache()

  call dein#add('Shougo/dein.vim',      {'rtp': ''})

  call dein#save_cache()
endif
```

After opening neovim, `:h dein`, says `E149: Sorry, no help for dein`. but it has help for the other plugins.

**Comment by wsdjeg** [comment]
change `let s:dein_path = expand('$CACHE/dein/repos/github.com/Shougo/dein.vim')`
to `let s:dein_path = expand('$CACHE/dein/dein.vim')`

**Comment by Shougo** [comment]
@PaBLoX-CL Please use `call dein#add('Shougo/dein.vim')` instead.
Fixed the documentation.

**Comment by prabirshrestha** [comment]
@Shougo Here is my full vimrc just to bootstrap dein.vim and I still can't seem to be able to load the doc.

```viml
set nocompatible

let g:settings = {}
let g:settings.cache_dir = expand('~/.config/nvim')
let g:settings.plugins_dir = g:settings.cache_dir . '/dein'
let g:settings.plugin_manager_dir = g:settings.plugins_dir . '/repos/github.com/Shougo/dein.vim'

if !filereadable(g:settings.plugin_manager_dir . '/README.md')
  if executable('git')
    echo "Installing dein.vim ..."
    echo ""
    execute printf('!git clone %s://github.com/Shougo/dein.vim --depth 1',
        \ (exists('$http_proxy') ? 'https' : 'git'))
        \ expand(g:settings.plugin_manager_dir)
  else
      echohl WarningMsg | echom "You need to install git!" | echohl None
  endif
endif

if has('vim_starting')
  exec 'set runtimepath^='.g:settings.plugin_manager_dir
endif

call dein#begin(g:settings.plugins_dir)
  if dein#load_cache()
    call dein#add('Shougo/dein.vim')
    call dein#add('Shougo/neocomplete.vim')
    call dein#save_cache()
  endif
call dein#end()

if dein#check_install()
  call dein#install()
endif

filetype plugin indent on
```

![image](https://cloud.githubusercontent.com/assets/287744/13204706/886542c0-d88b-11e5-80b3-1065db8e03c3.png)

**Comment by PaBLoX-CL** [comment]
@wsdjeg what's the difference?

@Shougo I tried that before, I should've state it sorry. It doesn't work :(

**Comment by Shougo** [comment]
Fixed the problem.
Please update dein.vim.
